import React from 'react';
import { motion } from 'framer-motion';
import { Sparkles, Zap, Target, Heart } from 'lucide-react';
import { OnboardingStepProps } from '../OnboardingFlow';
import Button from '../../Button';

/**
 * Welcome Step Component
 * 
 * Introduces users to the AI Workout application with:
 * - Engaging welcome message
 * - Key feature highlights
 * - Motivational content
 * - Smooth animations
 */
const WelcomeStep: React.FC<OnboardingStepProps> = ({
  onNext,
}) => {
  const features = [
    {
      icon: <Zap className="w-5 h-5" />,
      title: 'AI-Powered Workouts',
      description: 'Get personalized workouts generated by advanced AI',
    },
    {
      icon: <Target className="w-5 h-5" />,
      title: 'Goal-Oriented Training',
      description: 'Workouts tailored to your specific fitness goals',
    },
    {
      icon: <Heart className="w-5 h-5" />,
      title: 'Health-First Approach',
      description: 'Safe, effective workouts that prioritize your wellbeing',
    },
  ];

  return (
    <div className="text-center">
      {/* Welcome Message */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="mb-8"
      >
        <h3 className="text-3xl font-bold bg-gradient-to-r from-primary-600 to-blue-600 bg-clip-text text-transparent mb-4">
          Welcome to AI Workout! 🎉
        </h3>
        <p className="text-lg text-secondary-600 max-w-lg mx-auto">
          We're excited to help you achieve your fitness goals with personalized, 
          AI-generated workouts that adapt to your needs.
        </p>
      </motion.div>

      {/* Features Grid */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.4 }}
        className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8"
      >
        {features.map((feature, index) => (
          <motion.div
            key={feature.title}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 + index * 0.1 }}
            className="bg-gradient-to-br from-primary-50 to-blue-50 rounded-xl p-6 border border-primary-100"
          >
            <div className="bg-gradient-to-br from-primary-500 to-blue-600 w-12 h-12 rounded-lg flex items-center justify-center text-white mb-4 mx-auto">
              {feature.icon}
            </div>
            <h4 className="font-semibold text-secondary-900 mb-2">
              {feature.title}
            </h4>
            <p className="text-sm text-secondary-600">
              {feature.description}
            </p>
          </motion.div>
        ))}
      </motion.div>

      {/* Call to Action */}
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay: 0.8 }}
        className="bg-gradient-to-r from-primary-500 to-blue-600 rounded-xl p-6 text-white"
      >
        <Sparkles className="w-8 h-8 mx-auto mb-3" />
        <h4 className="text-xl font-semibold mb-2">
          Let's Get Started!
        </h4>
        <p className="text-primary-100 mb-4">
          It'll only take a few minutes to set up your personalized fitness profile.
        </p>
        <Button
          variant="secondary"
          size="lg"
          onClick={onNext}
          className="bg-white text-primary-600 hover:bg-primary-50"
        >
          Begin Setup
        </Button>
      </motion.div>
    </div>
  );
};

export default WelcomeStep;
